### ISSUE TITLE
Missing Dimension Null | Can't enter the server after dying | 1.16.5

### ISSUE THREAD

**Issue by Kayro098** [iPortalTeam/ImmersivePortalsMod#1158]
Hi.
I was playing in my world with this mod and when I died it kicked me out of the server, I tried to enter again but this error pops up:
**Internal Exception: io.netty.handler.codec.Encoder.Exception:java.lang.RuntimeException: Missing Dimension Null**

I've tried to delete and install again the mod but nothing seems to be working
It's a multiplayer world

**Comment by qouteall** [comment]
Unfortunately the 1.16.5 version is not being supported now.

**Comment by Kayro098** [comment]
> Unfortunately the 1.16.5 version is not being supported now.

Is there any way I can contact with someone that does help with 1.16.5?

**Comment by qouteall** [comment]
You seem to be using Forge. The 1.16.5 versions of the Forge version is outdated and incompatible with Forge's dynamic dimension system. It's recommended to stop using immptl 1.16.5 Forge version. There is no one maintaining the 1.16.5 Forge version now.

A new Forge version for 1.18.2 is being developed.
