### ISSUE TITLE
Game crashes on scaling with Pehkui

### ISSUE THREAD

**Issue by zemuffinnmann** [iPortalTeam/ImmersivePortalsMod#1266]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

No

### Describe the issue

when i walk thru the portal (1x1 to 2x2) it simply crashes the game.

[hs_err_pid22396.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10564554/hs_err_pid22396.log)

[modified to hide my name]

**Comment by zemuffinnmann** [comment]
btw the form says **_Farbic API_** instead of Fabric api, just so you know your typo

**Comment by zemuffinnmann** [comment]
![image](https://user-images.githubusercontent.com/124228260/216228688-6686ae91-8ac0-437c-b700-5b4684e10805.png)


list of mods

**Comment by qouteall** [comment]
According to the log, you seem to be using Nvidia videocard. The JVM crash is probably caused by an issue of Nvidia driver. You can install Sodium to workaround this issue https://github.com/CaffeineMC/sodium-fabric/issues/1486

**Comment by qouteall** [comment]
If it doesn't fix after using sodium, reopen the issue.

**Comment by zemuffinnmann** [comment]
i haven't installed sodium yet but it now runs at a lower framerate than usual so i might try to fix that just regularly
