### ISSUE TITLE
Error receiving packet 56 when teleporting

### ISSUE THREAD

**Issue by MehdiPG** [iPortalTeam/ImmersivePortalsMod#1494]
### Is it a mod compatibility issue?

No

### Minecraft version

1.18.x

### Describe the issue

The problem is that when using any teleportation method (commands, mod items, etc...), the server kicks the player with this error: Error receiving packet 56
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "dimension" is null.

I have tried removing all mods and plugins from the server and leaving only immersive portals, but the problem continues. I leave the log file [here](https://mclo.gs/fKWGbEG) and the error text [here](https://pastebin.com/raw/uDGUdxQz)

**Comment by Lolothepro** [comment]
arclight is not supported

**Comment by Lolothepro** [comment]
and wrong repo
