### ISSUE TITLE
Forgified portals

### ISSUE THREAD

**Issue by Arceus-77** [iPortalTeam/ImmersivePortalsMod#1642]
Would it be possible to make a forge port, preferably for 1.20.1, I know you may receive many suggestions like this one, but I really feel that many people would benefit from a forge port, I can't get connector to work.

**Comment by Nick1st** [comment]
Please stop spamming our trackers. My reason has been outlined many times before, please just accept it. Either switch to Fabric or update. We do not have the resources to support multiple outdated versions.
